import { Metadata } from "next";




export const metadata: Metadata = {
    title: "minimal",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body
          className="bg-black"
        >
          {children}
        </body>
      </html>
    );
  }
  